### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by Satanskiller** [WulfMarius/Food-Pack#4]
in update 1.30 and finding this mod to no longer be working

**Comment by WulfMarius** [comment]
Food-Pack is fully compatible with TLD V1.30

Make sure you have the latest version of the mod, as well as the latest version of [ModComponent](https://github.com/WulfMarius/ModComponent) and [AssetLoader](https://github.com/WulfMarius/AssetLoader).

If this doesn't resolve the issue, I will need some more information, like
What exactly is the problem?
Is there any kind of error message?
What's in the output_log.txt?

**Comment by Satanskiller** [comment]
i have searched all of mystery lake, pleasent valley, and coastal highway and have not found any modded items nor can i spawn in any with the commands, i have not seen any error codes

**Comment by WulfMarius** [comment]
Can you provider your output_log.txt?

This certainly sounds like the mod isn't installed properly.

**Comment by Satanskiller** [comment]
[output_log.txt](https://github.com/WulfMarius/Food-Pack/files/2042198/output_log.txt)

**Comment by WulfMarius** [comment]
The Mod-Loader appears to be installed and running, but the output shows that neither AssetLoader nor ModComponent is installed.

There should be something like this in the logfile:
>Calling OnLoad methods
[AssetLoader]: Version 2.0.1.0
[ModComponentMapper]: Version 2.1.1.0
[ModComponentMapper] Loading files from 'E:\Steam\steamapps\common\TheLongDark\mods\auto-mapped' ...
[AssetLoader]: Loading AssetBundle from 'E:\Steam\steamapps\common\TheLongDark\mods\auto-mapped\Food-Pack\Food-Pack.unity3d'.
[AssetLoader]: Processing asset 'Localization' as localization.
[AssetLoader]: Registered AssetBundle 'auto-mapped\Food-Pack\Food-Pack.unity3d' with the following assets
  gear_auroraenergydrink => assets/gear_auroraenergydrink.prefab
  gear_beerbottle => assets/gear_beerbottle.prefab
  gear_cannedchili => assets/gear_cannedchili.prefab
...

but your log contains none of this.

You should try re-installing AssetLoader, ModComponent and Food-Pack to resolve this.
Or maybe use the [Mod-Installer](https://github.com/WulfMarius/Mod-Installer/releases/latest).

**Comment by Satanskiller** [comment]
works correctly now, thank you many for the help much apriciated
