### ISSUE TITLE
Some question 

### ISSUE THREAD

**Issue by Whisper001** [WulfMarius/Food-Pack#5]
Thanks for the mod, but I do not fully understand its settings

item = AuroraEnergyDrink p = 6.4004,1.5805.0.6070 r = 0.181.5556.0 c = 80

The probability of a spawn is 80%?

And what does "w" mean in this line?

item = AuroraEnergyDrink w = 5

**Comment by WulfMarius** [comment]
Hi,

this a feature of ModComponent and described [here](https://github.com/WulfMarius/ModComponent/wiki/Gear-Spawns).

"c" is the chance to spawn when starting a new game.  
80 is 80%, 100 would mean a guaranteed spawn and 0 would never spawn.

"w" is the weight of the item in its loot table.  
This is a relative probability of the items being selected when chosing an item from their loot table. Higher values are more likely to be chosen.  
The page I linked above contains a link to a description of this selection type in wikipedia.

**Comment by Whisper001** [comment]
Thank you!
